### PR TITLE
add xtensor slides

### PR DESCRIPTION
**Pull request by wolfv**
Hey, do you accept the slides in this form?

Otherwise, I can check if I can make some sort of Firefox/Chrome compatible web-archive. 
PDF export looked bad, unfortunately.

Cheers!

Wolf

### CODE REVIEW

**Comment by wolfv** [comment]
Ok, just checked, there doesn't seem to be a natural way to create some sort of webarchive on linux chrome & firefox. 

I can zip the files and upload if that's better!

**Comment by jakeret** [comment]
Not sure if this is the most convenient way for someone who wants to quickly check out the material of that meetup

**Comment by wolfv** [comment]
I can upload the slides to e.g. the QuantStack website and post a link. Would that be better?

**Comment by betatim** [comment]
There is no way to render them to PDF?

**Pull request merged**
